INSERT INTO `util_job_categories` (`id`, `short_code`, `name`, `description`, `is_active`)
VALUES
	(1, NULL, 'Accounting & Finance', NULL, 1),
	(2, NULL, 'Management & Leadership', NULL, 1),
	(3, NULL, 'Clinicians', NULL, 1),
	(4, NULL, 'Administrative Support', NULL, 1),
	(5, NULL, 'Billing & Reimbursement', NULL, 1),
	(6, NULL, 'Organizational Compliance', NULL, 1),
	(7, NULL, 'Inventory Management', NULL, 1),
	(8, NULL, 'Credit & Collections', NULL, 1),
	(9, NULL, 'Customer Service', NULL, 1),
	(10, NULL, 'Distribution', NULL, 1),
	(11, NULL, 'Marketing & Sales', NULL, 1),
	(12, NULL, 'Repair & Service', NULL, 1),
	(13, NULL, 'Human Resources', NULL, 1),
	(14, NULL, 'Payroll', NULL, 1),
	(15, NULL, 'Pharmacy', NULL, 1),
	(16, NULL, 'Safety', NULL, 1),
	(17, NULL, 'Staff Education', NULL, 1),
	(18, NULL, 'Quality Assurance', NULL, 1),
	(19, NULL, 'Retail', NULL, 1),
	(20, NULL, 'Information Technology', NULL, 1),
	(21, NULL, 'Ancillary Staff', NULL, 1),
	(22, NULL, 'Religion & Spiritual', NULL, 1);
