INSERT INTO `util_course_categories` (`id`, `abbreviation`, `name`, `is_active`)
VALUES
	(1, 'AF', 'Accounting & Finance', 1),
	(2, 'AP', 'Anatomy & Physiology', 1),
	(3, 'AS', 'Administrative Support', 1),
	(4, 'BR', 'Billing & Reimbursement', 1),
	(5, 'CC', 'Credit & Collection', 1),
	(6, 'CL', 'Clinical', 1),
	(7, 'CS', 'Customer Service', 1),
	(8, 'CU', 'Custom Courses', 1),
	(9, 'DI', 'Distribution', 1),
	(10, 'DS', 'Diseases & Conditions', 1),
	(11, 'HC', 'Hospice & Respite Care', 1),
	(12, 'HR', 'Human Resources & Personnel', 1),
	(13, 'IM', 'Inventory Management', 1),
	(14, 'IT', 'Information Technology', 1),
	(15, 'MA', 'Medication Administration', 1),
	(16, 'ME', 'Medical Equipment', 1),
	(17, 'ML', 'Management & Leadership', 1),
	(18, 'SM', 'Sales & Marketing', 1),
	(19, 'OC', 'Organizational Compliance', 1),
	(20, 'PC', 'Patient Care', 1),
	(21, 'QA', 'Quality Assurance & Risk Management', 1),
	(22, 'RH', 'Rehabiltation', 1),
	(23, 'RO', 'Retail Operations', 1),
	(24, 'RS', 'Repair and Service', 1),
	(25, 'RX', 'Pharmacy', 1),
	(26, 'SE', 'Staff Education', 1),
	(27, 'SF', 'Safety (General)', 1),
	(28, 'SW', 'Software', 1),
	(29, 'TU', 'Tutorials', 1),
	(30, 'MS', 'Monthly Safety', 1),
	(31, 'HH', 'HHLEARN Specific Courses', 1);
