INSERT INTO `util_reg_agency_sub_classification` (`id`, `name`, `is_active`)
VALUES
	(1,'Accrediting Organization',1),
	(2,'Company Policy or Standard',1),
	(3,'Department of Labor',1),
	(4,'Department of Transportation',1),
	(5,'Equal Employment Opportunity Office',1),
	(6,'Emergency Management Office',1),
	(7,'Fair Employment Practice Agency',1),
	(8,'Home Medical Equipment Association',1),
	(9,'Hospice Organization',1),
	(10,'Medicaid Office',1),
	(11,'Medicare Office',1),
	(12,'Medicaid Fraud Unit',1),
	(13,'Medicare Fraud Unit',1),
	(14,'New Hire Agency',1),
	(15,'Board of Nursing',1),
	(16,'Nursing Organization',1),
	(17,'OSHA Office',1),
	(18,'Board of Pharmacy',1),
	(19,'Pharmacy Organization',1),
	(20,'Board of Respiratory Care',1),
	(21,'Respiratory Care Organization',1),
	(22,'Department of Health',1),
	(23,'Public Health and Safety Organization',1),
	(24,'Commercial Motor Vehicle Safety',1),
	(25,'Public (Non-Commercial) Motor Vehicle Safety',1),
	(26,'Drug Enforcement Agency Office',1),
	(27,'Internal Revenue Service Office',1),
	(28,'Immigration Office',1),
	(29,'Human Resources/Personnel',1),
	(30,'Civil Rights Organization',1),
	(31,'State Statutes',1),
	(32,'State Constitution',1),
	(33,'State Law',1),
	(34,'Elder Services',1),
	(35,'Medical Board',1),
	(36,'Physician Organization',1),
	(37,'Healthcare Standards Organization',1),
	(38,'Tuberculosis Control Office',1);
