INSERT INTO `util_videos` (`id`, `name`, `short_code`, `description`, `duration`, `cover`, `title`, `width`, `height`, `is_active`)
VALUES
	(7, 'Respirator Fit Testing', '', 'This video is about the respirator fit testing requirements for any worker who is required to use a tight-fitting respirator. The federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require employers to fit test workers who must wear these respirators on the job.', NULL, '48-7.png', '48-7.png', NULL, NULL, 1),
	(8, 'Pruebas de Ajuste de los Respiradores', '', 'Este video se ocupa de los requisitos sobre las pruebas de ajuste de los respiradores para todos los trabajadores que deben usar respiradores de ajuste hermético. La Administración de Seguridad y Salud Ocupacional - también llamada OSHA - y sus agencias estatales, exigen a los empleadores que hagan pruebas de ajuste a los empleados que deben usar respiradores en el trabajo.', NULL, '48-8.png', '48-8.png', NULL, NULL, 1),
	(9, 'Maintenance and Care of Respirators', '', 'This is a video about respirator maintenance and care requirements for any worker who wears a respirator. The federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require employers to have a respiratory protection program that includes provisions for the cleaning, disinfecting, inspection, repair, and storage of respirators used by workers on the job.', NULL, '48-9.png', '48-9.png', NULL, NULL, 1),
	(10, 'Mantenimiento Y Cuidado de los Respiradores', '', 'Este es un video sobre el mantenimiento y el cuidado de los equipos para los trabajadores que usan respiradores. La Administración de Seguridad y Salud Ocupacional - también llamada OSHA - y sus agencias estatales, exigen a los empleadores un programa de protección respiratoria que incluya disposiciones sobre la limpieza, desinfección, inspección, reparación y almacenamiento de los respiradores que utilizan los trabajadores.', NULL, '48-10.png', '48-10.png', NULL, NULL, 1),
	(11, 'Medical Evaluations for Workers Who Use Respirators', '', 'This video provides a brief overview and general information about medical evaluations that your employer must use to determine if you are able to wear a respirator. The federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require that employers provide these evaluations for free to all workers who are required to wear respirators on the job', NULL, '48-11.png', '48-11.png', NULL, NULL, 1),
	(12, 'Evaluaciones Médicas Para Trabajadores Que Usan Respiradores', '', 'Este video proporciona un breve resumen e información general sobre las evaluaciones médicas que su empleador debe utilizar para determinar si usted puede usar un respirador. La Administración de Seguridad y Salud Ocupacional federal - también llamada OSHA - y sus agencias estatales, exigen que los empleadores den en forma gratuita estas evaluaciones a todos sus empleados que deban usar respiradores en el trabajo.', NULL, '48-12.png', '48-12.png', NULL, NULL, 1),
	(14, 'Respirators Protection Training Requirements', '', 'This video is about the respiratory protection training requirements for any worker who is required to wear a respirator. The federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require employers to provide free respiratory protection training to workers who wear respirators on the job.', NULL, '48-14.png', '48-14.png', NULL, NULL, 1),
	(15, 'Los Requisitos de Capacitacion Para la Proteccion Respiratoria', '', 'Este video trata sobre los requisitos de capacitación para la protección respiratoria de todos los trabajadores que deben usar respiradores. La Administración de Seguridad y Salud Ocupacional Federal, también llamada OSHA, y sus agencias estatales, exigen a los empleadores que ofrecen programas gratuitos de capacitación sobre protección respiratoria a los empleados que deben usar respiradores en el trabajo.', NULL, '48-15.png', '48-15.png', NULL, NULL, 1),
	(16, 'Respirator Types', '', 'This is a video about the different types of respirators that workers might use in their workplace. If your employer requires you to wear a respirator on the job, the federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require that your employer select an appropriate respirator for you.', NULL, '48-16.png', '48-16.png', NULL, NULL, 1),
	(17, 'Tipos de Respiradores', '', 'Este es un video sobre los distintos tipos de respiradores que los trabajadores pueden usar en sus lugares de trabajo. Si debe usar un respirador en su trabajo, la Administración de Seguridad y Salud Ocupacional, también llamada OSHA, y sus agencias estatales, exigen a su empleador que elija un respirador adecuado para usted.', NULL, '48-17.png', '48-17.png', NULL, NULL, 1),
	(18, 'Voluntary Use of Respirators', '', 'This video is about the voluntary use of respirators in the workplace. Even though respirator use is not required in these situations, the federal Occupational Safety and Health Administration - also called \"OSHA\" - and State OSHA Agencies require employers to meet certain obligations for workers who voluntarily wear respirators on the job. This video discusses some of your employer\'s responsibilities under OSHA\'s respiratory protection voluntary use requirements.', NULL, '48-18.png', '48-18.png', NULL, NULL, 1),
	(19, 'Uso Voluntario de Respiradores', '', 'Este video se ocupa del uso voluntario de respiradores en el lugar de trabajo. Aún cuando el uso de respiradores no es obligatorio en estas situaciones, la Administración de Seguridad y Salud Ocupacional, también llamada OSHA, y sus agencias estatales, exigen a los empleadores que cumplan con ciertas obligaciones cuando los trabajadores desean usar respiradores voluntariamente en sus trabajos. Este video explica algunas de las responsabilidades de su empleador según los requisitos de la OSHA para el uso voluntario de protección respiratoria.', NULL, '48-19.png', '48-19.png', NULL, NULL, 1),
	(20, 'Counterfeit and Altered Respirators:  The Importance of Checking for NIOSH Certification', '', 'This video provides a brief overview and general information about counterfeit and altered respirators and the importance of making sure that a respirator is certified by the National Institute for Occupational Safety and Health, also known as NIOSH. Employers are responsible for selecting appropriate respirators for their workers, and this video will assist them in making such a selection. This information is also good for both workers and their employers to understand the potential consequences of counterfeit and altered respirators.', NULL, '48-20.png', '48-20.png', NULL, NULL, 1),
	(22, 'Inside the Brain: Unraveling the Mystery of Alzheimer\'s Disease', '', 'This 4-minute captioned video shows the intricate mechanisms involved in the progression of Alzheimer\'s disease in the brain.', NULL, '58-22.png', '58-22.jpg', NULL, NULL, 1),
	(26, 'Drowsy Driving', '', 'The CMV driver is traveling in the right lane of a two-lane highway on wet pavement during the day. The driver becomes distracted with something out his right window as traffic begins to slow ahead of him. The driver returns focus to the forward roadway and has to brake quickly and move into the left lane.', '00:00:31', '32-26.png', '32-26.png', NULL, NULL, 1);
